baseURL = "/"
languageCode = "en-us"
title = "TechSlayers"


[menu]

    [[menu.main]]
        name = "Home"
        url = "/"
        weight= 1    

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
    
    [[menu.main]]
        name = "Courses"
        url = "/courses"
        weight= 2    

    [[menu.main]]
        name = "Contact"
        url = "/contact"

    [[menu.main]]
        name = "FAQ<empty>"
        url = "/"    
    




# For the Theme import, for team members on project to render SITE
[module]
    [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"


[params]
  favicon = ""
  site_logo = "/img/TechSlayers_logo.png"
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  body_classes = ""
  post_content_classes = ""
  featured_image = "/img/serverBanner.jpg"
  recent_posts_number = 2




