baseURL = "/"
languageCode = "en-us"
title = "TechSlayers"
# theme = "ananke"



[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

    [[menu.main]]
        name = "Contact"
        url = "/contact"


# For the Theme import, for team members on project to render SITE
[module]
    [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"


[params]
  favicon = ""
  site_logo = "/img/TechSlayers_logo.png"
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = ""
  recent_posts_number = 2




